#!/bin/sh
./build || exit

list_fail=""

check()
	{
	local name="$1"
	echo "test $name"
	../bin/fexl test/$name.fxl 2>&1 | diff - out/$name
	if [ $? -eq 1 ]; then
		list_fail="$list_fail $name"
	fi
	}

refresh()
	{
	local name="$1"
	echo "refresh $name"
	../bin/fexl test/$name.fxl 2>&1 | cat >tmp/$name
	}

list="$@"

# Run all tests by default.
if [ "$list" = "" ]; then
	list="$list a1 a2 a3 a4 a5 a6 a7 a8 a9 b10"
	list="$list b11 b12 b13 b14 b15 b16 b17 b18 b19 b20"
	list="$list b21 b22 b23 b24 b25 b26 b27 b28 b29 b30"
	list="$list b31 b32 b33 b34 b35 b36 b37 b38 b39 b40"
	list="$list b41 b42 b43 b44 b45 b46"
fi

do_check()
	{
	list_fail=""
	for name in $list; do
		check $name
	done
	if [ "$list_fail" = "" ]; then
		echo "All tests succeeded"
	else
		echo "These tests failed:$list_fail"
		exit 1
	fi
	}

do_refresh()
	{
	rm -rf tmp
	mkdir tmp
	for name in $list; do
		refresh $name
	done
	}

do_check
#do_refresh
