#!/bin/sh    # for syntax highlighting only
# Handy shell functions for development and testing.  You can source these in a
# new shell with ". alias".

.todo()
	{
	grep -ra TODO build test src --exclude=".*.swp"
	}

.build()
	{
	./build quiet
	}

.fexl()
	{
	.build && bin/fexl $1
	}

.s()
	{
	grep -r $1 src/*
	}

# Run a test script.
.run()
	{
	.build &&
	bin/fexl "test/$1.fxl"
	}

# Check that the output of a test script equals its reference output.  I use
# the "cat" form here in case the script uses interactive input like char_get.
.check()
	{
	.build &&
	cat "test/$1.fxl" | bin/fexl | diff -a - "test/$1.out"
	}

# Time a test script, also checking its output.
.time()
	{
	.build &&
	time (cat "test/$1.fxl" | bin/fexl | diff -a - "test/$1.out")
	}

# git status
.gs()
	{
	git status
	}

# git diff (-a treats binary files as text)
.gd()
	{
	git diff -a $1
	}
