#!/bin/sh
. ./config
(cd $base/src && ./build) || exit

make_obj math assert limits
make_obj rlimit $base/die stdio sys/resource

common="$base/str $base/value $base/type $base/type_str $base/type_sym"
make_obj show stdio $common

modules="math rlimit $base/buf $base/memory $base/die $common $base/parse show"
make_obj run stdio sys/resource $modules
make_bin run $modules
