#!/bin/sh
. ./config

# TODO elim
testing="stdio ../../test/src/show"

make_obj type value
make_obj die stdarg stdio stdlib
make_obj memory die assert stdlib
make_obj str memory assert string
make_obj type_str str value
make_obj type_sym memory str value type type_str
make_obj value die memory
make_obj buf memory str assert string
make_obj parse buf ctype die str value type type_sym  $testing
