extern value type_C(value f);
extern value type_S(value f);
extern value type_I(value f);
extern value type_F(value f);
extern value type_R(value f);
extern value type_L(value f);
extern value type_Y(value f);
extern value type_later(value f);
extern value type_query(value f);
extern value type_halt(value f);
extern value type_pair(value f);
extern value type_cons(value f);
extern value pair(value x, value y);
extern value cons(value x, value y);
extern value C;
extern value S;
extern value I;
extern value R;
extern value L;
extern value Y;
extern value query;
extern value Qpair;
extern value Qcons;
extern void beg_basic(void);
extern void end_basic(void);
