extern value type_T(value f);
extern value type_F(value f);
extern value type_Y(value f);
extern value type_eval(value f);
extern value type_once(value f);
extern value type_void(value f);
extern value type_yield(value f);
extern value type_cons(value f);
extern value type_null(value f);
extern value op_is_type(value f, type t);
extern value type_is_void(value f);
extern value type_is_good(value f);
extern value type_is_bool(value f);
extern value type_is_list(value f);
extern struct value QT;
extern struct value QF;
extern struct value Qeval;
extern struct value Qcons;
extern struct value Qnull;
extern struct value Qvoid;
extern struct value Qyield;
extern value reduce_void(value f);
extern value reduce_boolean(value f, int x);
extern value yield(value x);
