#!/bin/sh

# Run a system command and exit if unsuccessful.
run()
	{
	#echo $@  # enable for trace
	$@
	local code=$?
	if [ $code -ne 0 ]; then exit $code; fi
	}

cmd_compile="gcc -c -Wall -Werror -Wunused-parameter -ansi -pedantic -O3 -I ."
cmd_link="gcc -s -lm"

compile()
	{
	local name="$1"
	local file_o=../obj/$name.o
	objects="$objects $file_o"
	run $cmd_compile $name.c -o $file_o
	}

link()
	{
	local name="$1"
	shift
	run $cmd_link $@ -o ../bin/$name
	}

./clean

mkdir -p ../obj
mkdir -p ../bin

objects=""
compile basic
compile buffer
compile die
compile format
compile input
compile memory
compile num
compile output
compile parse
compile source
compile str
compile type_cmp
compile type_convert
compile type_input
compile type_math
compile type_num
compile type_output
compile type_str
compile type_sym
compile type_sys
compile value

# LATER make a library
common=$objects

objects=""
compile define
compile fexl

link fexl $common $objects
