#!/bin/sh
. ./lib_build
make basic
make buffer
make convert
make die
make fexl
make file
make file2
make format
make input
make limit
make memory
make num
make parse
make report
make str
make type_buf
make type_cmp
make type_file
make type_form
make type_input
make type_istr
make type_limit
make type_math
make type_num
make type_output
make type_parse
make type_rand
make type_resolve
make type_run
make type_standard
make type_str
make type_sym
make type_var
make value
# These are used only during development.
if false; then
make output
make output2
make show
fi
link fexl
