#!/bin/sh
./build || exit

# Disable core dump.
ulimit -Sc 0

# Limit stack and virtual memory in 1K blocks.
ulimit -Ss 40000
ulimit -Sv 100000

# Limit CPU time in seconds.
ulimit -St 20

../bin/fexl "$@"
