#!/bin/sh
# These are common shell routines used by test scripts, sourced with ".".

do_time()
	{
	local usr_cmd="$1"
	local cmd="\
TIMEFORMAT=\"time %2Rs\"
time $usr_cmd"
	/bin/bash -c "$cmd" 2>&1
	}

doing()
	{
	local name="$1"
	echo -n "do $name: "
	}

do_diff()
	{
	local prog="$1"
	local out="$2"
	doing $prog
	do_time "$prog | diff - $out"
	}

do_diff_fexl()
	{
	local name="$1"
	local prog="../bin/fexl test/$name.fxl"
	local out="test/$name.out"
	doing $name
	do_time "$prog | diff - $out"
	}
