extern struct value *type_long(struct value *);
extern struct value *Qlong(long);
extern long get_long(struct value *);
extern struct value *type_long_add(struct value *);
extern struct value *type_long_sub(struct value *);
extern struct value *type_long_mul(struct value *);
extern struct value *type_long_div(struct value *);
extern struct value *type_is_long(struct value *);
extern struct value *type_long_double(struct value *);
extern struct value *type_long_string(struct value *);
extern struct value *type_long_compare(struct value *);
extern struct value *type_long_char(struct value *);
