#!/bin/sh
# Example of configuring the build script to link with external objects

return  # Pound me out to try linking with external "fred" code.

# Tell the compiler where to find fred's include files.
include="$include -I ../../fred/src"

find_module()
	{
	local module="$1"
	if [ $module = "fred" ]; then
		# Link with external fred.o if you #include "fred.h".
		echo ../../fred/obj/$module.o
	fi
	}
