extern int main_argc;
extern char **main_argv;
extern char **main_envp;
extern int main_exit;
extern long line;
extern long max_depth;
extern long cur_depth;
extern long max_steps;
extern long cur_steps;
extern void beg_run(int argc, char *argv[], char *envp[]);
