extern value type_use_standard(value f);
extern value type_use_numbers(value f);
extern value QI;
extern value QT;
extern value QF;
extern value QY;
extern value Qvoid;
extern value Qcons;
extern value Qnull;
extern value Qeval;
extern value Qlater;
extern value Qput;
extern value Qnl;
extern value Qfput;
extern value Qfnl;
extern value Qtuple;
extern value Qparse_file;
extern value Qevaluate;
extern value Quse_standard;
extern void eval_standard(int argc, char *argv[]);
