extern value type_standard(value f);
extern value Qsubst;
extern value Qtuple;
extern value QI;
extern value QT;
extern value QF;
extern value QY;
extern value Qvoid;
extern value Qcons;
extern value Qnull;
extern value Qeval;
extern value Qlater;
extern value Qput;
extern value Qnl;
extern value Qfput;
extern value Qfnl;
extern value Qparse_file;
extern value Qevaluate;
extern void eval_standard(int argc, const char *argv[]);
