extern value type_string(value);
extern value Qchars(char *data, long len);
extern value Qcopy_chars(const char *data, long len);
extern value Qcopy_string(const char *data);
extern char *string_data(value);
extern long string_len(value);
extern int string_compare(value, value);
extern int string_eq(value, value);
extern int string_long(char *beg, long *num);
extern int string_double(char *beg, double *num);
extern value type_is_string(value);
extern value type_string_compare(value);
extern value type_string_slice(value);
extern value type_string_append(value);
extern value type_string_len(value);
extern value type_string_long(value);
extern value type_string_double(value);
extern value type_string_at(value);
extern value type_string_common(value);
