extern value type_double(value f);
extern value Qdouble(double val);
extern double get_double(value f);
extern int string_double(const char *beg, double *num);
extern value type_double_add(value f);
extern value type_double_sub(value f);
extern value type_double_mul(value f);
extern value type_double_div(value f);
extern value type_double_cmp(value f);
extern value type_double_string(value f);
extern value type_double_long(value f);
