extern value Qput;
extern value Qnl;
extern value Qfput;
extern value Qfnl;
extern value type_put(value fun, value f);
extern value type_nl(value fun, value f);
extern value type_say(value fun, value f);
extern value type_fput(value fun, value f);
extern value type_fnl(value fun, value f);
extern value type_fsay(value fun, value f);
extern value type_fflush(value fun, value f);
extern void beg_output(void);
extern void end_output(void);
