extern value Qstdin;
extern value Qstdout;
extern value Qstderr;
extern value type_file(value fun, value f);
extern value Qfile(FILE *fh);
extern FILE *get_fh(value x);
extern value type_fopen(value fun, value f);
extern value type_fclose(value fun, value f);
extern value type_fgetc(value fun, value f);
extern value type_fget(value fun, value f);
extern value type_clearerr(value fun, value f);
extern value type_feof(value fun, value f);
extern value type_flook(value fun, value f);
extern value type_remove(value fun, value f);
extern value type_is_newer(value fun, value f);
extern value type_is_file(value fun, value f);
extern value type_is_dir(value fun, value f);
extern value type_flock_ex(value fun, value f);
extern value type_flock_sh(value fun, value f);
extern value type_flock_un(value fun, value f);
extern value type_readlink(value fun, value f);
extern value type_mkdir(value fun, value f);
extern value type_rmdir(value fun, value f);
extern value type_ftruncate(value fun, value f);
extern value type_fseek_set(value fun, value f);
extern value type_fseek_cur(value fun, value f);
extern value type_fseek_end(value fun, value f);
extern value type_ftell(value fun, value f);
extern value type_fileno(value fun, value f);
extern value type_fread(value fun, value f);
extern value type_mkfile(value fun, value f);
extern value type_dir_names(value fun, value f);
extern value type_mod_time(value fun, value f);
extern value type_file_size(value fun, value f);
extern value type_symlink(value fun, value f);
extern value type_rename(value fun, value f);
extern void beg_file(void);
extern void end_file(void);
