extern value Qempty;
extern value type_record(value fun, value arg);
extern value def(value key, value val, value obj);
extern value type_def(value fun, value arg);
extern value type_set(value fun, value arg);
extern value type_get(value fun, value arg);
extern value chain(value new, value old);
extern value type_chain(value fun, value arg);
extern value type_record_pairs(value fun, value arg);
extern void beg_record(void);
extern void end_record(void);
