extern int main_argc;
extern const char **main_argv;
extern value type_die(value fun, value f);
extern value type_argv(value fun, value f);
extern value type_sleep(value fun, value f);
extern value type_usleep(value fun, value f);
extern value type_run_process(value fun, value f);
extern value type_spawn(value fun, value f);
extern value type_start_server(value fun, value f);
extern value type_kill(value fun, value f);
extern value type_connect(value fun, value f);
extern value type_exec(value fun, value f);
extern value type_receive_keystrokes(value fun, value f);
extern value type_fexl_benchmark(value fun, value f);
