extern void close_random(void);
extern value type_random_bytes(value f);
extern value type_random_nonce(value f);
extern value type_random_secret_key(value f);
extern value type_crypto_box_public(value f);
extern value type_crypto_box_prepare(value f);
extern value type_crypto_box_seal(value f);
extern value type_crypto_box_open(value f);
extern value type_crypto_sign_public(value f);
extern value type_crypto_sign_seal(value f);
extern value type_crypto_sign_open(value f);
extern value type_crypto_hash(value f);
