extern string get_str(value x);
extern value type_str(value fun, value f);
extern value Qstr(string x);
extern value Qstr0(const char *data);
extern const char *str_data(value x);
extern value op_str(value fun, value f, string op(string));
extern value op_str2(value fun, value f, string op(string,string));
extern value op_str3(value fun, value f, string op(string,string,string));
extern value type_concat(value fun, value f);
extern value type_length(value fun, value f);
extern value type_slice(value fun, value f);
extern value type_search(value fun, value f);
extern value type_str_num(value fun, value f);
extern value type_ord(value fun, value f);
extern value type_chr(value fun, value f);
extern value type_char_width(value fun, value f);
extern value type_dirname(value fun, value f);
extern value type_basename(value fun, value f);
extern value type_length_common(value fun, value f);
extern value type_compare_at(value fun, value f);
extern value type_is_str(value fun, value f);
extern value op_argv(value fun, value f, value op(const char *const *argv));
