extern value type_add(value fun, value f);
extern value type_sub(value fun, value f);
extern value type_mul(value fun, value f);
extern value type_div(value fun, value f);
extern value type_pow(value fun, value f);
extern value type_xor(value fun, value f);
extern value type_round(value fun, value f);
extern value type_ceil(value fun, value f);
extern value type_trunc(value fun, value f);
extern value type_abs(value fun, value f);
extern value type_sqrt(value fun, value f);
extern value type_exp(value fun, value f);
extern value type_log(value fun, value f);
extern value type_sin(value fun, value f);
extern value type_cos(value fun, value f);
extern const double num_pi;
