extern value type_add(value f);
extern value type_sub(value f);
extern value type_mul(value f);
extern value type_div(value f);
extern value type_pow(value f);
extern value type_round(value f);
extern value type_trunc(value f);
extern value type_abs(value f);
extern value type_sqrt(value f);
