extern value type_str(value f);
extern value Qstr(string x);
extern value Qstr0(const char *data);
extern string get_str(value x);
extern const char *str_data(value x);
extern value type_concat(value f);
extern value type_length(value f);
extern value type_slice(value f);
extern value type_search(value f);
extern value type_str_num(value f);
extern value type_ord(value f);
extern value type_chr(value f);
extern value type_char_width(value f);
extern value type_is_str(value f);
