extern value type_quo(value f);
extern value type_ref(value f);
extern value quo(value val);
extern value ref(string name, unsigned long line);
extern value join(type t, value x, value y);
extern value app(value x, value y);
extern value lam(type type, string name, value exp);
extern value type_form(value f);
extern value Qform(value label, value exp);
extern value type_D(value f);
extern value type_E(value f);
extern value type_is_closed(value f);
extern value type_def(value f);
extern int match(const char *other);
extern value op_context(value f, value define(void));
extern value type_value(value f);
extern value type_resolve(value f);
extern value type_evaluate(value f);
extern value type_extend(value f);
extern value type_form_undefs(value f);
extern value type_form_refs(value f);
extern void beg_sym(void);
extern void end_sym(void);
