extern value type_long(value f);
extern value Qlong(long val);
extern long get_long(value f);
extern int string_long(const char *beg, long *num);
extern value type_long_add(value f);
extern value type_long_sub(value f);
extern value type_long_mul(value f);
extern value type_long_div(value f);
extern value type_long_cmp(value f);
extern value type_long_string(value f);
extern value type_order(value f);
extern value type_long_char(value f);
