extern value type_C(value f, value g);
extern value type_I(value f, value g);
extern value type_S(value f, value g);
extern value type_L(value f, value g);
extern value type_R(value f, value g);
extern value type_Y(value f, value g);
extern value type_query(value f, value g);
extern value type_pair(value f, value g);
extern value type_cons(value f, value g);
extern value pair(value x, value y);
extern value cons(value x, value y);
extern value C;
extern value I;
extern value S;
extern value L;
extern value R;
extern value Y;
extern value query;
extern value Qpair;
extern value Qcons;
extern void beg_base(void);
extern void end_base(void);
